### ISSUE TITLE
LC_COUNTY label 오타 확인 요청

### ISSUE THREAD

**Issue by parkce** [korean-named-entity/konne#1]
안녕하세요.
레이블 오타 제보드립니다.

LC_COUNTY로 레이블링 되어 있습니다. 
문장을 보니 LCP_COUNTY가 맞는 거 같아요.

* TRAIN SET

{"id": 256, "klue_id": "klue-ner-v1_train_00255_wikitree", "text": "이밖에 인근 취징시 후이쩌현에선 6명이 목숨을 잃었다고 현지 언론이 전한 바 있다.", "label": [[7, 10, "LCP_CITY"], [11, 15, "LC_COUNTY"], [18, 20, "QT_MAN_COUNT"]]}

{"id": 2323, "klue_id": "klue-ner-v1_train_02322_wikitree", "text": "산둥성 가오미(高密)현 출신인 모옌은 고향의 전설을 바탕으로 근·현대 중국인이 걸어온 역사의 궤적을 생생한 필체로 담아냈다는 평가를 받고 있다.", "label": [[0, 3, "LCP_PROVINCE"], [4, 12, "LC_COUNTY"], [17, 19, "PS_NAME"], [39, 42, "CV_TRIBE"]]}

{"id": 3692, "klue_id": "klue-ner-v1_train_03691_wikitree", "text": "일본의 일방적인 독도 영유권 주장의 일환인 '다케시마(竹島·독도의 일본식 명칭)의 날' 행사가 22일 아베 내각 당국자와 여야 국회의원들이 참
석한 가운데 일본 시마네(島根)현에서 열린다.", "label": [[0, 2, "LCP_COUNTRY"], [9, 11, "LCG_ISLAND"], [24, 51, "EV_OTHERS"], [25, 29, "LCG_ISLAND"], [30, 32, "LCG_ISLAND"], [33, 35, "LCG_ISLAND"], [37, 39, "LCP_COUNTRY"], [53, 56, "DT_DAY"], [57, 59, "PS_NAME"], [71, 75, "CV_POSITION"], [86, 88, "LCP_COUNTRY"], [86, 97, "LC_COUNTY"], [89, 97, "LC_COUNTY"]]}

{"id": 13619, "klue_id": "klue-ner-v1_train_13618_wikitree", "text": "한편 아베 총리는 이날 정상회담에서 오바마 대통령에게 자신의 지역구가 있는 야마구치(山口)현 토산 술인 '다사이(獺祭)'와 유리 세공 전문>가가 만든 술잔을 선물했다.", "label": [[3, 5, "PS_NAME"], [3, 8, "PS_NAME"], [6, 8, "CV_POSITION"], [10, 12, "DT_DAY"], [13, 17, "EV_OTHERS"], [20, 23, "PS_NAME"], [20, 27, "PS_NAME"], [24, 27, "CV_POSITION"], [42, 51, "LC_COUNTY"], [59, 66, "CV_DRINK"], [69, 71, "MT_CHEMICAL"]]}

{"id": 15498, "klue_id": "klue-ner-v1_train_15497_wikitree", "text": "이란(宜蘭)현에서는 바닷가에서 놀던 쌍둥이 딸 모녀가 파도에 휩쓸려 2명이 숨지고 1명이 실종됐다.", "label": [[0, 7, "LC_COUNTY"], [20, 23, "CV_RELATION"], [24, 25, "CV_RELATION"], [26, 28, "CV_RELATION"], [38, 40, "QT_MAN_COUNT"], [46, 48, "QT_MAN_COUNT"]]}

{"id": 15776, "klue_id": "klue-ner-v1_train_15775_wikitree", "text": "15일 일본 후쿠시마(福島)현 앞바다에서 리히터 규모 5.1의 지진이 발생했다.", "label": [[0, 3, "DT_DAY"], [4, 6, "LCP_COUNTRY"], [4, 16, "LC_COUNTY"], [7, 11, "LCP_COUNTY"], [12, 14, "LCP_PROVINCE"], [15, 16, "LC_COUNTY"], [27, 33, "QT_OTHERS"]]}

{"id": 17591, "klue_id": "klue-ner-v1_train_17590_wikitree", "text": "시마네현에 지역구가 있는 호소다 히로유키(細田博之) 자민당 간사당 대행(중의원) 등 일본의 여야 국회의원 16명(가메오카 정무관 제외)도 참
석할 예정이다.", "label": [[0, 4, "LC_COUNTY"], [14, 28, "PS_NAME"], [29, 32, "OGG_POLITICS"], [40, 43, "CV_POSITION"], [47, 49, "LCP_COUNTRY"], [54, 58, "CV_POSITION"], [59, 62, "QT_MAN_COUNT"], [63, 67,

{"id": 18270, "klue_id": "klue-ner-v1_train_18269_wikitree", "text": "일본 시마네현은 매년 2월 22일을 '다케시마(일본이 주장하는 독도 명칭)의 날’로 정해 행사를 개최하고 있다.", "label": [[0, 2, "LCP_COUNTRY"], [3, 7, "LC_COUNTY"], [12, 14, "DT_MONTH"], [15, 18, "DT_DAY"], [21, 25, "LCG_ISLAND"], [26, 28, "LCP_COUNTRY"], [35, 37, "LCG_ISLAND"]]}

* DEV SET

{"id": 21748, "klue_id": "klue-ner-v1_dev_00739-wikitree", "text": "수사팀은 39년 전 김씨가 주민등록증에 부착했던 사진과 지문 자료를 지난해 11월 일본 인터폴에 제공했고 일본 사이타마현 경찰청은 김씨 검거>를 위한 전담팀 구성 7일 만인 올 3월24일 김씨를 체포했다.", "label": [[5, 10, "DT_OTHERS"], [11, 12, "PS_NAME"], [38, 41, "DT_YEAR"], [38, 45, "DT_OTHERS"], [42, 45, "DT_MONTH"], [46, 48, "LCP_COUNTRY"], [49, 52, "OGG_LAW"], [59, 61, "LCP_COUNTRY"], [59, 71, "OGG_POLITICS"], [62, 67, "LC_COUNTY"], [68, 71, "OGG_POLITICS"], [73, 74, "PS_NAME"], [90, 94, "DT_DURATION"], [96, 103, "DT_OTHERS"], [98, 100, "DT_MONTH"], [100, 103, "DT_DAY"], [104, 105, "PS_NAME"]]}

{"id": 22688, "klue_id": "klue-ner-v1_dev_01679-wikitree", "text": "뤄 할머니가 거주하고 있는 바마야오족자치현은 주민 10만명 중 100살을 넘는 노인이 30.8명일 정도로 유명한 장수촌이랍니다.", "label": [[0, 1, "PS_NAME"], [2, 5, "CV_RELATION"], [15, 20, "CV_TRIBE"], [15, 23, "LC_COUNTY"], [28, 32, "QT_MAN_COUNT"], [35, 39, "QT_AGE"], [48, 53, "QT_MAN_COUNT"]]}

{"id": 23546, "klue_id": "klue-ner-v1_dev_02537-wikitree", "text": "이어 오후 2시20분경 지바현 북부 노다시에서도 돌풍이 발생해 다수의 주택이 피해를 봤습니다.", "label": [[3, 12, "TI_OTHERS"], [6, 8, "TI_HOUR"], [8, 11, "TI_MINUTE"], [13, 16, "LC_COUNTY"], [13, 23, "LCP_CITY"], [17, 19, "TM_DIRECTION"], [20, 23, "LCP_CITY"]]}

{"id": 23789, "klue_id": "klue-ner-v1_dev_02780-wikitree", "text": "스타벅스 측이 수입하기로 한 그린티 파우더는 원전 사고가 발생한 후쿠시마와 약간 떨어진 아이치현 소재 '교토와아이치'에서 생산된 것이라고 하는데요.", "label": [[0, 4, "OGG_FOOD"], [16, 23, "CV_FOOD"], [36, 40, "LCP_COUNTY"], [49, 53, "LC_COUNTY"], [58, 60, "LCP_COUNTRY"], [58, 64, "OGG_ECONOMY"]]}

{"id": 24810, "klue_id": "klue-ner-v1_dev_03801-wikitree", "text": "이날 오전 1시 25분께 일본 규슈 구마모토현에서 발생한 강진 이후 부산에서는 진동을 감지한 시민의 신고가 1천965건에 달했다.", "label": [[0, 2, "DT_DAY"], [3, 5, "TI_DURATION"], [3, 13, "TI_OTHERS"], [6, 8, "TI_HOUR"], [9, 12, "TI_MINUTE"], [14, 16, "LCP_COUNTRY"], [17, 19, "LCP_PROVINCE"], [20, 25, "LC_COUNTY"], [38, 40, "LCP_CITY"], [60, 66, "QT_COUNT"]]}

{"id": 25018, "klue_id": "klue-ner-v1_dev_04009-wikitree", "text": "대회에서 1등 한 사람에게는 오카야마 현에서 생산된 쌀 90kg이 상품으로 주어졌다.", "label": [[5, 7, "QT_ORDER"], [8, 12, "QT_MAN_COUNT"], [16, 22, "LC_COUNTY"], [29, 30, "PT_FRUIT"], [31, 35, "QT_WEIGHT"]]}

**Comment by youhyunjo** [comment]
감사합니다! 수정하겠습니다. 전체적으로 라벨 오류가 있는지도 검사해 보겠습니다.
